from __future__ import annotations
from pathlib import Path
from pyblocks.blocks.editor.model import CustomBlockDef

_HEADER = """\
# Auto-generated by PyBlocks Block Editor — do not edit manually
from pyblocks.blocks.definition import block

"""

_BLOCK_TMPL = """\
@block(label={label!r}, category={category!r}, color={color!r},
       description={description!r})
def {name}({params}) -> str:
    return {body!r}

"""

class BlockFileWriter:

    @staticmethod
    def write(project_root: Path, defns: list[CustomBlockDef]) -> Path:
        exp_dir = project_root / "expansions"
        exp_dir.mkdir(exist_ok=True)
        out = exp_dir / "custom_blocks.py"

        parts = [_HEADER]
        for d in defns:
            if not d.is_valid():
                continue
            params = ", ".join(d.inputs) if d.inputs else ""
            parts.append(_BLOCK_TMPL.format(
                label=d.label,
                category=d.category,
                color=d.color,
                description=d.description,
                name=d.name,
                params=params,
                body=d.template,
            ))
        out.write_text("".join(parts), encoding="utf-8")
        return out
